language: android
jdk: oraclejdk8
sudo: required

branches:
  only:
    - master

script: "./gradlew clean assembleDebug"

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
  - "$HOME/android/.gradle/caches/"
  - "$HOME/android/.gradle/wrapper/"

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - tools
    - android-26
    - addon-google_apis-google-26
    - extra-google-m2repository
    - extra-android-m2repository
    - android-sdk-license-.+

  licenses:
      - 'android.+'
      - 'google.+'

